name:                xmonad-config
version:             0.1.0.0
github:              "githubuser/xmonad"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/xmonad#readme>

dependencies:
- base >= 4.7 && < 5
- process
- containers
- directory
- unix
- X11
- xmonad
- xmonad-contrib

library:
  source-dirs: .

executables:
  xmonad-exe:
    main:                xmonad.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmonad-config

tests:
  xmonad-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmonad-config

